name: Deploy Azure Infrastructure

on:
  workflow_dispatch:
    inputs:
      organization:
        description: "Organization folder under apps/"
        required: true
        default: vzcorp
      project:
        description: "Project folder under apps/{organization}/"
        required: true
        default: agentsAssemble

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    name: "Deploy workload for ${{ inputs.organization }} / ${{ inputs.project }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login via Azure CLI using Federated Identity
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Make deployment script executable
        working-directory: apps/${{ inputs.organization }}/${{ inputs.project }}
        run: chmod +x deployment.sh

      - name: Execute deployment script
        working-directory: apps/${{ inputs.organization }}/${{ inputs.project }}
        run: ./deployment.sh